### ISSUE TITLE
Unable to initialize call recorder 

### ISSUE THREAD

**Issue by Deval99** [di72nn/callrecorder-axet#7]
Whenever i open the app, call recorder works 2-3 days. Then it just stops, and then every time i call, i get a Toast "Unable to initialize call recorder" (Dont know exactly the Toast message, but i read something like that). Again if i open the app, it starts working again. Settings of this app is default (Battery optimization is disabled and i tried switching recording calls to "System Default" but still stops working after sometime). 

More Info:
Device : ASUS X00TD
ROM : Pixel Experience (Android 11)
Rooted Device

**Comment by di72nn** [comment]
If call recording works at all, then this module works. If things break after a couple of days, the problem is probably somewhere else.

You can try to use normal installation of the the app (without this magisk module, even if it doesn't record calls properly) simply to see if the same problem reappears. If it does (I think it will), it probably has something to do with system optimizations or the app not being able to properly work on your ROM.

You can also check system logcat whenever you see that "Unable to initialize call recorder".

And I also found [a similar issue](https://gitlab.com/axet/android-call-recorder/-/issues/166) in the app repo (*this* repo is for the magisk module only).
